"""What a service needs from its surroundings, described structurally.

The application layer never imports an adapter. Services receive a
:class:`ServiceContext` (the composition root's container) and open units of
work through it; everything they touch is typed against the Protocols below,
which ``adapters.db`` (repositories, ORM rows), ``adapters.storage`` (layout)
and the gateways wired in ``copycast.app`` satisfy at runtime. The boundary
itself is dynamic: SQLAlchemy's ``Mapped`` descriptors are not statically
assignable to these row protocols, so the container exposes its factory and
layout untyped and the worker uses the concrete classes directly.
"""

from __future__ import annotations

import uuid
from collections.abc import Awaitable, Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Literal, Protocol

from pydantic import BaseModel

from copycast.application.models import (
    CatalogCounts,
    FeedCredentials,
    PodcastSearchResult,
    ProbeCandidate,
    Totals,
    VideoSearchResult,
)
from copycast.application.ports import CancelToken, Engine
from copycast.domain.enums import (
    ArchiveState,
    AssetFormat,
    AssetKind,
    AssetProvenance,
    AssetState,
    FeedKind,
    JobKind,
    JobStatus,
    JobTrigger,
    KeyScope,
    LogLevel,
    Numbering,
    RefreshRunStatus,
    RequestedVia,
    SourceKind,
    WantedReason,
)
from copycast.domain.listing import SourceListing
from copycast.domain.selection import ResolvedSelection, SelectionCandidate
from copycast.settings import Settings

FeedSort = Literal["title", "created_at", "updated_at", "storage_bytes"]
ItemSort = Literal["published", "ordinal", "title", "added"]
Order = Literal["asc", "desc"]

# --------------------------------------------------------------------------- rows


class FeedRow(Protocol):
    """A ``feeds`` row; policy and metadata columns are mutable through the session."""

    @property
    def id(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def is_default(self) -> bool: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def storage_bytes(self) -> int: ...
    @property
    def revision(self) -> int: ...
    @property
    def intent_version(self) -> int: ...
    @property
    def last_refresh_attempt_at(self) -> datetime | None: ...
    @property
    def last_refresh_success_at(self) -> datetime | None: ...
    @property
    def last_error(self) -> str | None: ...

    title: str
    title_override: str | None
    description: str | None
    author: str | None
    artwork_url: str | None
    language: str | None
    auth_username: str
    auth_password: str
    source_url: str | None
    source_dedup_key: str | None
    source_kind: str | None
    service: str | None
    source_channel_xml: str | None
    source_etag: str | None
    source_last_modified: str | None
    backfill_mode: str | None
    backfill_latest_n: int | None
    min_duration_seconds: int | None
    preferred_language: str | None
    retention_days: int | None
    follow: bool
    paused: bool
    policy_applied_at: datetime | None
    engine_options: dict[str, Any]
    autoprune_days: int | None
    last_autoprune_at: datetime | None


class ItemRow(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def feed_id(self) -> str: ...
    @property
    def source_key(self) -> str: ...
    @property
    def ordinal(self) -> int: ...
    @property
    def source_number(self) -> int | None: ...
    @property
    def source_season(self) -> int | None: ...
    @property
    def title(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def author(self) -> str | None: ...
    @property
    def artwork_url(self) -> str | None: ...
    @property
    def published_at(self) -> datetime | None: ...
    @property
    def duration_seconds(self) -> int | None: ...
    @property
    def source_url(self) -> str | None: ...
    @property
    def archivable(self) -> bool: ...
    @property
    def listed(self) -> bool: ...
    @property
    def first_seen_at(self) -> datetime: ...
    @property
    def archive_state(self) -> str: ...
    @property
    def wanted_reason(self) -> str | None: ...
    @property
    def attempt_count(self) -> int: ...
    @property
    def last_error(self) -> str | None: ...
    @property
    def archived_at(self) -> datetime | None: ...
    @property
    def media_path(self) -> str | None: ...
    @property
    def media_mime(self) -> str | None: ...
    @property
    def media_bytes(self) -> int | None: ...
    @property
    def media_ext(self) -> str | None: ...
    @property
    def download_count(self) -> int: ...
    @property
    def first_downloaded_at(self) -> datetime | None: ...
    @property
    def last_downloaded_at(self) -> datetime | None: ...


class AssetRow(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def feed_id(self) -> str: ...
    @property
    def item_id(self) -> str | None: ...
    @property
    def kind(self) -> str: ...
    @property
    def provenance(self) -> str: ...
    @property
    def language(self) -> str | None: ...
    @property
    def format(self) -> str | None: ...
    @property
    def remote_url(self) -> str | None: ...
    @property
    def local_path(self) -> str | None: ...
    @property
    def mime(self) -> str | None: ...
    @property
    def size_bytes(self) -> int | None: ...
    @property
    def state(self) -> str: ...
    @property
    def last_error(self) -> str | None: ...
    @property
    def fetched_at(self) -> datetime | None: ...


class JobRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def kind(self) -> str: ...
    @property
    def trigger(self) -> str: ...
    @property
    def feed_id(self) -> str | None: ...
    @property
    def item_id(self) -> str | None: ...
    @property
    def request_id(self) -> uuid.UUID | None: ...
    @property
    def payload(self) -> dict[str, Any]: ...
    @property
    def status(self) -> str: ...
    @property
    def priority(self) -> int: ...
    @property
    def attempt(self) -> int: ...
    @property
    def max_attempts(self) -> int: ...
    @property
    def cancel_requested(self) -> bool: ...
    @property
    def progress(self) -> dict[str, Any] | None: ...
    @property
    def result(self) -> dict[str, Any] | None: ...
    @property
    def error(self) -> str | None: ...
    @property
    def error_kind(self) -> str | None: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def started_at(self) -> datetime | None: ...
    @property
    def finished_at(self) -> datetime | None: ...
    @property
    def is_active(self) -> bool: ...


class RequestRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def feed_id(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def requested_via(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def item_count(self) -> int: ...
    @property
    def error(self) -> str | None: ...
    @property
    def created_at(self) -> datetime: ...


class ApiKeyRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def name(self) -> str: ...
    @property
    def scope(self) -> str: ...
    @property
    def prefix(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def last_used_at(self) -> datetime | None: ...


class RefreshRunRow(Protocol):
    @property
    def id(self) -> int: ...


class HeartbeatRow(Protocol):
    @property
    def worker_id(self) -> str: ...
    @property
    def seen_at(self) -> datetime: ...
    @property
    def status(self) -> dict[str, Any]: ...


class ListingUpsertResult(Protocol):
    @property
    def listed_count(self) -> int: ...
    @property
    def new_count(self) -> int: ...
    @property
    def delisted_count(self) -> int: ...
    @property
    def new_item_ids(self) -> list[str]: ...
    @property
    def seen_item_ids(self) -> list[str]: ...
    @property
    def wanted_item_ids(self) -> list[str]: ...


# --------------------------------------------------------------------------- repositories


class FeedRepositoryPort(Protocol):
    async def get(self, feed_id: str) -> FeedRow | None: ...
    async def require(self, feed_id: str) -> FeedRow: ...
    async def get_for_update(self, feed_id: str) -> FeedRow: ...
    async def by_dedup_key(self, dedup_key: str) -> FeedRow | None: ...
    async def mirrors_due_expiry(self, before: datetime) -> Sequence[FeedRow]: ...
    async def list(
        self, kind: FeedKind | None = None, *, sort: FeedSort = "title", order: Order = "asc"
    ) -> Sequence[FeedRow]: ...
    async def find_inbox(self, ident: str) -> FeedRow | None: ...
    async def default_inbox(self) -> FeedRow | None: ...
    async def totals(self) -> Totals: ...
    async def add(self, feed: Any) -> FeedRow: ...
    async def delete(self, feed_id: str) -> bool: ...
    async def ensure_default_inbox(self, title: str = ...) -> FeedRow: ...
    async def bump_revision(self, feed_id: str) -> int: ...
    async def recount_storage(self, feed_id: str) -> int: ...
    async def apply_metadata(
        self,
        feed_id: str,
        *,
        title: str | None = None,
        description: str | None = None,
        author: str | None = None,
        artwork_url: str | None = None,
        language: str | None = None,
        service: str | None = None,
    ) -> None: ...


class CatalogRepositoryPort(Protocol):
    async def get(self, item_id: str) -> ItemRow | None: ...
    async def require(self, item_id: str, feed_id: str | None = None) -> ItemRow: ...
    async def get_many(self, item_ids: Iterable[str]) -> Sequence[ItemRow]: ...
    async def list_page(
        self,
        feed_id: str,
        *,
        state: ArchiveState | Sequence[ArchiveState] | None = None,
        listed: bool | None = None,
        q: str | None = None,
        sort: ItemSort = "published",
        order: Order = "desc",
        limit: int = 100,
        offset: int = 0,
    ) -> tuple[Sequence[ItemRow], int]: ...
    async def count_by_state(self, feed_id: str) -> CatalogCounts: ...
    async def count_by_state_many(self, feed_ids: Iterable[str]) -> dict[str, CatalogCounts]: ...
    async def selection_candidates(self, feed_id: str) -> Sequence[SelectionCandidate]: ...
    async def resolve_numbers(
        self,
        feed_id: str,
        *,
        numbers: Sequence[int] = (),
        item_ids: Sequence[str] = (),
        numbering: Numbering = Numbering.source,
    ) -> ResolvedSelection: ...
    async def ids_in_state(self, feed_id: str, state: ArchiveState) -> Sequence[str]: ...
    async def available_ids(
        self,
        feed_id: str,
        *,
        first_seen_after: datetime | None = None,
        latest_n: int | None = None,
        min_duration_seconds: int | None = None,
        include_deleted: bool = False,
    ) -> Sequence[str]: ...
    async def window_ids(
        self, feed_id: str, size: int, *, min_duration_seconds: int | None = None
    ) -> Sequence[str]: ...
    async def prunable(
        self,
        feed_id: str,
        *,
        downloaded: bool = False,
        added_before: datetime | None = None,
        downloaded_before: datetime | None = None,
        last_activity_before: datetime | None = None,
    ) -> Sequence[ItemRow]: ...
    async def upsert_listing(
        self,
        feed_id: str,
        listing: SourceListing,
        *,
        now: datetime | None = None,
        wanted_reason: WantedReason | None = None,
    ) -> ListingUpsertResult: ...
    async def set_wanted(self, item_ids: Iterable[str], reason: WantedReason) -> Sequence[str]: ...
    async def mark_state(
        self,
        item_id: str,
        state: ArchiveState,
        *,
        only_from: ArchiveState | Sequence[ArchiveState] | None = None,
        error: str | None = None,
        count_attempt: bool = False,
        media_path: str | None = None,
        media_mime: str | None = None,
        media_bytes: int | None = None,
        duration_seconds: int | None = None,
        archived_at: datetime | None = None,
        wanted_reason: WantedReason | None = None,
    ) -> bool: ...
    async def tombstone(
        self, item_id: str, *, listed: bool, at: datetime | None = None
    ) -> bool: ...
    async def record_download(self, item_id: str, at: datetime | None = None) -> bool: ...


class AssetRepositoryPort(Protocol):
    async def for_item(self, item_id: str) -> Sequence[AssetRow]: ...
    async def for_items(self, item_ids: Iterable[str]) -> Mapping[str, Sequence[AssetRow]]: ...
    async def feed_artwork(self, feed_id: str) -> AssetRow | None: ...
    async def upsert(
        self,
        feed_id: str,
        item_id: str | None,
        kind: AssetKind,
        *,
        provenance: AssetProvenance = AssetProvenance.mirrored,
        language: str | None = None,
        format: AssetFormat | None = None,
        remote_url: str | None = None,
        local_path: str | None = None,
        mime: str | None = None,
        size_bytes: int | None = None,
        state: AssetState = AssetState.wanted,
        last_error: str | None = None,
        fetched_at: datetime | None = None,
        slot: str | None = None,
    ) -> AssetRow: ...
    async def delete_for_item(self, item_id: str) -> Sequence[AssetRow]: ...


class RequestRepositoryPort(Protocol):
    async def get(self, request_id: uuid.UUID) -> RequestRow | None: ...
    async def require(self, request_id: uuid.UUID, feed_id: str | None = None) -> RequestRow: ...
    async def add(
        self, feed_id: str, url: str, via: RequestedVia, *, request_id: uuid.UUID | None = None
    ) -> RequestRow: ...
    async def list_page(
        self, feed_id: str, *, limit: int = 100, offset: int = 0
    ) -> tuple[Sequence[RequestRow], int]: ...
    async def count_for_feeds(self, feed_ids: Iterable[str]) -> Mapping[str, int]: ...
    async def link_items(self, request_id: uuid.UUID, item_ids: Iterable[str]) -> int: ...
    async def item_ids(self, request_id: uuid.UUID) -> Sequence[str]: ...
    async def item_ids_many(
        self, request_ids: Iterable[uuid.UUID]
    ) -> Mapping[uuid.UUID, Sequence[str]]: ...
    async def request_ids_for_items(
        self, item_ids: Iterable[str]
    ) -> Mapping[str, Sequence[uuid.UUID]]: ...
    async def mark_expanded(
        self, request_id: uuid.UUID, item_count: int, *, at: datetime | None = None
    ) -> None: ...
    async def mark_failed(self, request_id: uuid.UUID, error: str) -> None: ...


class JobRepositoryPort(Protocol):
    async def get(self, job_id: uuid.UUID) -> JobRow | None: ...
    async def require(self, job_id: uuid.UUID) -> JobRow: ...
    async def list_page(
        self,
        *,
        feed_id: str | None = None,
        kind: JobKind | None = None,
        status: JobStatus | Sequence[JobStatus] | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> tuple[Sequence[JobRow], int]: ...
    async def active(
        self, *, feed_id: str | None = None, kind: JobKind | None = None
    ) -> Sequence[JobRow]: ...
    async def active_by_dedup_key(self, key: str) -> JobRow | None: ...
    async def latest_for_request(self, request_id: uuid.UUID) -> JobRow | None: ...
    async def latest_for_item(self, item_id: str) -> JobRow | None: ...
    async def enqueue(
        self,
        kind: JobKind,
        trigger: JobTrigger,
        *,
        feed_id: str | None = None,
        item_id: str | None = None,
        request_id: uuid.UUID | None = None,
        payload: dict[str, Any] | None = None,
        priority: int = ...,
        max_attempts: int | None = None,
        run_after: datetime | None = None,
        dedup: str | None = None,
        job_id: uuid.UUID | None = None,
    ) -> JobRow | None: ...
    async def cancel(self, job_id: uuid.UUID) -> JobRow: ...
    async def cancel_for_feed(
        self, feed_id: str, *, kinds: Iterable[JobKind] | None = None
    ) -> int: ...
    async def requeue_stale(self, older_than: timedelta) -> Sequence[uuid.UUID]: ...
    async def purge_finished(self, before: datetime) -> int: ...
    async def append_log(
        self, job_id: uuid.UUID, lines: Sequence[tuple[int, datetime, LogLevel, str]]
    ) -> int: ...


class ApiKeyRepositoryPort(Protocol):
    async def get(self, key_id: uuid.UUID) -> ApiKeyRow | None: ...
    async def require(self, key_id: uuid.UUID) -> ApiKeyRow: ...
    async def by_hash(self, key_hash: str) -> ApiKeyRow | None: ...
    async def list(self) -> Sequence[ApiKeyRow]: ...
    async def add(self, *, name: str, scope: KeyScope, key_hash: str, prefix: str) -> ApiKeyRow: ...
    async def delete(self, key_id: uuid.UUID) -> bool: ...
    async def touch(self, key_id: uuid.UUID, at: datetime | None = None) -> None: ...


class TelemetryRepositoryPort(Protocol):
    async def start_refresh_run(
        self, feed_id: str, *, trigger: JobTrigger, job_id: uuid.UUID | None = None
    ) -> RefreshRunRow: ...
    async def finish_refresh_run(
        self,
        run_id: int,
        status: RefreshRunStatus,
        *,
        listed_count: int = 0,
        new_count: int = 0,
        delisted_count: int = 0,
        wanted_count: int = 0,
        error: str | None = None,
        engine_version: str | None = None,
    ) -> None: ...
    async def purge_refresh_runs(self, before: datetime) -> int: ...
    async def heartbeat(self, worker_id: str, status: dict[str, Any]) -> None: ...
    async def latest_heartbeat(self) -> HeartbeatRow | None: ...
    async def record_engine_version(
        self,
        version: str,
        *,
        channel: str | None = None,
        release_date: Any = None,
        git_head: str | None = None,
        app_version: str | None = None,
    ) -> Any: ...


# --------------------------------------------------------------------------- unit of work


class LayoutPort(Protocol):
    """The slice of ``adapters.storage.layout.Layout`` the services and jobs use."""

    def read_version(self) -> str | None: ...
    def cookies_path(self) -> Path: ...
    def defaults_path(self) -> Path: ...
    def feed_dir(self, feed_id: str) -> Path: ...
    def source_xml_path(self, feed_id: str) -> Path: ...
    def source_listing_path(self, feed_id: str) -> Path: ...
    def media_dir(self, feed_id: str) -> Path: ...
    def tmp_dir(self, feed_id: str) -> Path: ...
    def assets_dir(self, feed_id: str) -> Path: ...
    def info_json_path(self, feed_id: str, item_id: str) -> Path: ...
    def item_xml_path(self, feed_id: str, item_id: str) -> Path: ...
    def relative(self, feed_id: str, path: Path) -> str: ...
    def resolve(self, feed_id: str, relative: str) -> Path: ...
    def ensure_feed_dirs(self, feed_id: str) -> Path: ...
    def remove_tmp_leftovers(self, feed_id: str, item_id: str) -> int: ...
    def remove_feed(self, feed_id: str) -> bool: ...


Hook = Callable[[], Awaitable[None] | None]


class UnitOfWorkPort(Protocol):
    """One transaction: ``async with ctx.uow_factory() as uow`` commits on a clean exit."""

    @property
    def feeds(self) -> FeedRepositoryPort: ...
    @property
    def catalog(self) -> CatalogRepositoryPort: ...
    @property
    def assets(self) -> AssetRepositoryPort: ...
    @property
    def requests(self) -> RequestRepositoryPort: ...
    @property
    def jobs(self) -> JobRepositoryPort: ...
    @property
    def telemetry(self) -> TelemetryRepositoryPort: ...
    @property
    def api_keys(self) -> ApiKeyRepositoryPort: ...
    @property
    def layout(self) -> LayoutPort: ...

    def after_commit(self, hook: Hook) -> None: ...
    async def update_intent(self, feed_id: str, *, debounce: bool = False) -> tuple[int, int]: ...
    async def bump_revision(self, feed_id: str) -> int: ...
    async def publish(self, event: BaseModel) -> None: ...
    async def notify_jobs(self, payload: str = "") -> None: ...
    async def flush(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def __aenter__(self) -> UnitOfWorkPort: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...


class UnitOfWorkFactoryPort(Protocol):
    def __call__(self) -> UnitOfWorkPort: ...
    async def flush_exports(self) -> None: ...
    async def aclose(self) -> None: ...


# --------------------------------------------------------------------------- gateways


@dataclass(frozen=True, slots=True)
class SourceSnapshot:
    """One probed Source: the candidate, its listing and, for RSS, the verbatim document.

    ``channel_xml`` is the ``<rss>`` root minus items (``feeds.source_channel_xml``);
    ``body`` is what ``source/feed.xml`` receives. yt-dlp Sources carry the
    listing only (``source/listing.json`` is written from ``listing.raw``).
    """

    candidate: ProbeCandidate
    listing: SourceListing
    body: bytes | None = None
    etag: str | None = None
    last_modified: str | None = None
    channel_xml: str | None = None

    @property
    def source_url(self) -> str:
        return self.candidate.source_url

    @property
    def source_kind(self) -> SourceKind:
        return self.candidate.source_kind


class SourceGateway(Protocol):
    """Probing, searching and Source snapshots; every method is synchronous and blocking."""

    def probe(
        self, url: str, *, options: Mapping[str, Any], cancel: CancelToken
    ) -> list[SourceSnapshot]: ...
    def cached(self, *, token: str | None, url: str | None) -> SourceSnapshot | None: ...
    def search_podcasts(self, query: str, limit: int) -> list[PodcastSearchResult]: ...
    def search_videos(self, query: str, limit: int) -> list[VideoSearchResult]: ...
    def save_snapshot(self, feed_id: str, snapshot: SourceSnapshot) -> None: ...


class PublicUrls(Protocol):
    """The URLs Copycast publishes (``adapters.feeds.urls`` bound to ``base_url``).

    While authentication is on, ``feed_url`` carries the feed's own pair as
    ``user:pass@`` and ``feed_credentials`` exposes it; otherwise both stay bare.
    """

    def feed_url(
        self, feed_id: str, *, username: str | None = None, password: str | None = None
    ) -> str: ...
    def feed_credentials(self, username: str, password: str) -> FeedCredentials | None: ...
    def media_url(self, feed_id: str, item_id: str, ext: str) -> str: ...
    def asset_url(self, feed_id: str, local_path: str) -> str: ...


class RowFactory(Protocol):
    """Builds new ORM rows the repositories have no constructor for."""

    def feed(self, **values: Any) -> Any: ...


class ServiceContext(Protocol):
    """The container as the services see it."""

    @property
    def settings(self) -> Settings: ...
    @property
    def engine(self) -> Engine: ...
    @property
    def uow_factory(self) -> UnitOfWorkFactoryPort: ...
    @property
    def layout(self) -> LayoutPort: ...
    @property
    def sources(self) -> SourceGateway: ...
    @property
    def urls(self) -> PublicUrls: ...
    @property
    def rows(self) -> RowFactory: ...


__all__ = [
    "ApiKeyRepositoryPort",
    "ApiKeyRow",
    "AssetRepositoryPort",
    "AssetRow",
    "CatalogRepositoryPort",
    "FeedRepositoryPort",
    "FeedRow",
    "FeedSort",
    "HeartbeatRow",
    "Hook",
    "ItemRow",
    "ItemSort",
    "JobRepositoryPort",
    "JobRow",
    "LayoutPort",
    "ListingUpsertResult",
    "Order",
    "PublicUrls",
    "RefreshRunRow",
    "RequestRepositoryPort",
    "RequestRow",
    "RowFactory",
    "ServiceContext",
    "SourceGateway",
    "SourceSnapshot",
    "TelemetryRepositoryPort",
    "UnitOfWorkFactoryPort",
    "UnitOfWorkPort",
]
