/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as JobsRouteImport } from "./routes/jobs";
import { Route as KeysRouteImport } from "./routes/keys";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as InboxesIndexRouteImport } from "./routes/inboxes/index";
import { Route as InboxesInboxIdRouteImport } from "./routes/inboxes/$inboxId";
import { Route as MirrorsIndexRouteImport } from "./routes/mirrors/index";
import { Route as MirrorsMirrorIdRouteImport } from "./routes/mirrors/$mirrorId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const JobsRoute = JobsRouteImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => rootRouteImport,
} as any);
const KeysRoute = KeysRouteImport.update({
  id: "/keys",
  path: "/keys",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const InboxesIndexRoute = InboxesIndexRouteImport.update({
  id: "/inboxes/",
  path: "/inboxes/",
  getParentRoute: () => rootRouteImport,
} as any);
const InboxesInboxIdRoute = InboxesInboxIdRouteImport.update({
  id: "/inboxes/$inboxId",
  path: "/inboxes/$inboxId",
  getParentRoute: () => rootRouteImport,
} as any);
const MirrorsIndexRoute = MirrorsIndexRouteImport.update({
  id: "/mirrors/",
  path: "/mirrors/",
  getParentRoute: () => rootRouteImport,
} as any);
const MirrorsMirrorIdRoute = MirrorsMirrorIdRouteImport.update({
  id: "/mirrors/$mirrorId",
  path: "/mirrors/$mirrorId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/jobs": typeof JobsRoute;
  "/keys": typeof KeysRoute;
  "/settings": typeof SettingsRoute;
  "/inboxes/$inboxId": typeof InboxesInboxIdRoute;
  "/mirrors/$mirrorId": typeof MirrorsMirrorIdRoute;
  "/inboxes/": typeof InboxesIndexRoute;
  "/mirrors/": typeof MirrorsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/jobs": typeof JobsRoute;
  "/keys": typeof KeysRoute;
  "/settings": typeof SettingsRoute;
  "/inboxes/$inboxId": typeof InboxesInboxIdRoute;
  "/mirrors/$mirrorId": typeof MirrorsMirrorIdRoute;
  "/inboxes": typeof InboxesIndexRoute;
  "/mirrors": typeof MirrorsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/jobs": typeof JobsRoute;
  "/keys": typeof KeysRoute;
  "/settings": typeof SettingsRoute;
  "/inboxes/$inboxId": typeof InboxesInboxIdRoute;
  "/mirrors/$mirrorId": typeof MirrorsMirrorIdRoute;
  "/inboxes/": typeof InboxesIndexRoute;
  "/mirrors/": typeof MirrorsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/jobs"
    | "/keys"
    | "/settings"
    | "/inboxes/$inboxId"
    | "/mirrors/$mirrorId"
    | "/inboxes/"
    | "/mirrors/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/jobs"
    | "/keys"
    | "/settings"
    | "/inboxes/$inboxId"
    | "/mirrors/$mirrorId"
    | "/inboxes"
    | "/mirrors";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/jobs"
    | "/keys"
    | "/settings"
    | "/inboxes/$inboxId"
    | "/mirrors/$mirrorId"
    | "/inboxes/"
    | "/mirrors/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  JobsRoute: typeof JobsRoute;
  KeysRoute: typeof KeysRoute;
  SettingsRoute: typeof SettingsRoute;
  InboxesInboxIdRoute: typeof InboxesInboxIdRoute;
  MirrorsMirrorIdRoute: typeof MirrorsMirrorIdRoute;
  InboxesIndexRoute: typeof InboxesIndexRoute;
  MirrorsIndexRoute: typeof MirrorsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/jobs": {
      id: "/jobs";
      path: "/jobs";
      fullPath: "/jobs";
      preLoaderRoute: typeof JobsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/keys": {
      id: "/keys";
      path: "/keys";
      fullPath: "/keys";
      preLoaderRoute: typeof KeysRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/inboxes/": {
      id: "/inboxes/";
      path: "/inboxes";
      fullPath: "/inboxes/";
      preLoaderRoute: typeof InboxesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/inboxes/$inboxId": {
      id: "/inboxes/$inboxId";
      path: "/inboxes/$inboxId";
      fullPath: "/inboxes/$inboxId";
      preLoaderRoute: typeof InboxesInboxIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/mirrors/": {
      id: "/mirrors/";
      path: "/mirrors";
      fullPath: "/mirrors/";
      preLoaderRoute: typeof MirrorsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/mirrors/$mirrorId": {
      id: "/mirrors/$mirrorId";
      path: "/mirrors/$mirrorId";
      fullPath: "/mirrors/$mirrorId";
      preLoaderRoute: typeof MirrorsMirrorIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JobsRoute: JobsRoute,
  KeysRoute: KeysRoute,
  SettingsRoute: SettingsRoute,
  InboxesInboxIdRoute: InboxesInboxIdRoute,
  MirrorsMirrorIdRoute: MirrorsMirrorIdRoute,
  InboxesIndexRoute: InboxesIndexRoute,
  MirrorsIndexRoute: MirrorsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
