class YoutubeDLError(Exception):
    msg: str | None
    def __init__(self, msg: str | None = None) -> None: ...

class ExtractorError(YoutubeDLError):
    expected: bool
    video_id: str | None
    ie: str | None
    cause: BaseException | None
    def __init__(
        self,
        msg: str,
        tb: str | None = None,
        expected: bool = False,
        cause: BaseException | None = None,
        video_id: str | None = None,
        ie: str | None = None,
    ) -> None: ...

class UnavailableVideoError(YoutubeDLError): ...

class GeoRestrictedError(ExtractorError):
    countries: list[str] | None
    def __init__(self, msg: str, countries: list[str] | None = None, **kwargs: object) -> None: ...

class DownloadError(YoutubeDLError):
    exc_info: object
    def __init__(self, msg: str, exc_info: object = None) -> None: ...

class DownloadCancelled(YoutubeDLError): ...
class ThrottledDownload(YoutubeDLError): ...
class PostProcessingError(YoutubeDLError): ...
class SameFileError(YoutubeDLError): ...
class MaxDownloadsReached(DownloadCancelled): ...
class ExistingVideoReached(DownloadCancelled): ...
class RejectedVideoError(DownloadCancelled): ...

def replace_extension(filename: str, ext: str, expected_real_ext: str | None = None) -> str: ...
